AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
    join:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: src/join.handler
          Runtime: nodejs6.10
          Description: ''
          MemorySize: 128
          Timeout: 15
          Role: arn:aws:iam::966887599552:role/ilab-bot-functions
          Environment:
            Variables:
              REGION: ap-northeast-1
    prior:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: src/prior.handler
          Runtime: nodejs6.10
          Description: ''
          MemorySize: 128
          Timeout: 15
          Role: arn:aws:iam::966887599552:role/ilab-bot-functions
          Environment:
            Variables:
              REGION: ap-northeast-1
    race:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: src/race.handler
          Runtime: nodejs6.10
          Description: ''
          MemorySize: 128
          Timeout: 15
          Role: arn:aws:iam::966887599552:role/ilab-bot-functions
          Environment:
            Variables:
              REGION: ap-northeast-1